Repository aviyelverse/Hacktoberfest-with-Aviyel, pull requests merged in 2022-11, with the labels that each got.

#57 Hacktoberfest Submission
  week-1/pramitmarattha.md
Labels: hacktoberfest

#60 sriniketh-contributions
  final-week/sriniketh_novu.md
  week-1/sriniketh_general.md
  week-2/sriniketh_keploy.md
Labels: hacktoberfest

#63 Create How_Novu_Made_Email_Notifications_Easy_For_Businesses.md
  final-week/ZohebAhmed_novu.md
Labels: hacktoberfest

#64 Create funkeolasupo_reactplay.md
  final-week/funkeolasupo_reactplay.md
Labels: hacktoberfest, hacktoberfest-accepted

#70 created docs
  final-week/khushalsarode_metacall.md
  final-week/khushalsarode_novuhd.md
  week-2/khushalsarode_metacall.md
Labels: hacktoberfest, hacktoberfest-accepted

#68 Create gayatridunakhe_general.md
  week-1/gayatridunakhe_general.md
  week-2/gayatridunakhe_general.md
Labels: hacktoberfest, hacktoberfest-accepted

#66 Week2 article
  week-2/ZohebAhmed_week2.md
Labels: hacktoberfest, hacktoberfest-accepted

#71 Update and rename ZohebAhmed_week2.md to ZohebAhmed_reactplay.md
  week-2/ZohebAhmed_reactplay.md
Labels: enhancement, hacktoberfest

#65 Create iqrafirdose_code.md
  final-week/iqrafirdose_novu.md
  week-1/iqrafirdose_general.md
  week-2/iqrafirdose_general.md
Labels: hacktoberfest, hacktoberfest-accepted

#73 week1 article added
  week-1/ZohebAhmed_week1.md
Labels: hacktoberfest

#75 create iqrafirdose_testsigma.md
  final-week/iqrafirdose_testsigma.md
Labels: hacktoberfest

#79 Update PR_GREET.yml
  .github/workflows/PR_GREET.yml
Labels: enhancement

#89 Create Boluwatife_Fayemi_General.md
  week-1/Boluwatife_Fayemi_General.md
Labels: hacktoberfest
